import {auth, signIn, signOut} from "@/auth";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {CheckCheckIcon} from 'lucide-react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const email = session?.user?.email;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <header className="bg-blue-950 p-2">
          <div className="max-w-sm justify-between mx-auto flex items-center">
            <Link
              className="inline-flex gap-1 items-center text-xl"
              href={'/'}>
              <span className="bg-blue-600 rounded-lg p-0.5">
                <CheckCheckIcon />
              </span>
              Todoer
            </Link>
            <nav>
              {!email && (
                <form
                  action={async () => {
                    "use server"
                    await signIn("google")
                  }}
                >
                  <button type="submit">Sign in</button>
                </form>
              )}
              {email && (
                <form
                  action={async () => {
                    "use server"
                    await signOut();
                  }}
                >
                  <button type="submit">
                    Sign out
                  </button>
                </form>
              )}
            </nav>
          </div>
        </header>
        <main className="p-2">
          <div className="max-w-sm mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
